FROM python:3.11.10-slim-bookworm AS api


WORKDIR /app

COPY requirements.txt .
COPY api/models.pu .
COPY api/api.py .

RUN pip install -r requirements.txt

ENV QUESTDB_HOST=questdb

EXPOSE 8000

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]